name: Linters
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # version v4.1.7
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - name: Setup GO
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # version v5.0.2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # version v6.0.1
        with:
          version: v1.52.2 # this is the golangci-lint version
          args: --issues-exit-code=0 # exit without errors for now - won't fail the build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true




