name: Linters
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # version v3.0.2
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - name: Setup GO
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # version v5.0.2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # version v6.1.0
        with:
          version: v1.52.2 # this is the golangci-lint version
          args: --issues-exit-code=0 # exit without errors for now - won't fail the build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true




